# Generated by Django 5.0.2 on 2024-02-23 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longUrl', models.URLField(unique=True)),
                ('shorUrl', models.URLField(unique=True)),
            ],
        ),
    ]
